
-- 500 Soal Kuis Fiqih (10 soal per subbab)

-- Bab Fiqih
INSERT INTO bab_fiqih (judul, deskripsi) VALUES
('Thaharah (Bersuci)', 'Hukum air, wudhu, mandi, tayamum, najis'),
('Shalat', 'Syarat, rukun, macam-macam shalat'),
('Puasa (Shaum)', 'Syarat, jenis, hal yang membatalkan'),
('Zakat', 'Jenis zakat, nisab, mustahik, waktu'),
('Haji dan Umrah', 'Rukun, wajib, sunnah, larangan');

-- Subbab Fiqih
INSERT INTO subbab_fiqih (id_bab, judul, deskripsi) VALUES
(1, 'Pengertian Thaharah', 'Pembahasan tentang Pengertian Thaharah'),
(1, 'Macam-macam Air', 'Pembahasan tentang Macam-macam Air'),
(1, 'Air yang Mensucikan', 'Pembahasan tentang Air yang Mensucikan'),
(1, 'Air Musta’mal', 'Pembahasan tentang Air Musta’mal'),
(1, 'Najis dan Cara Mensucikan', 'Pembahasan tentang Najis dan Cara Mensucikan'),
(1, 'Tayamum', 'Pembahasan tentang Tayamum'),
(1, 'Wudhu dan Rukunnya', 'Pembahasan tentang Wudhu dan Rukunnya'),
(1, 'Sunnah Wudhu', 'Pembahasan tentang Sunnah Wudhu'),
(1, 'Hal yang Membatalkan Wudhu', 'Pembahasan tentang Hal yang Membatalkan Wudhu'),
(1, 'Mandi Wajib', 'Pembahasan tentang Mandi Wajib'),
(2, 'Syarat Wajib Shalat', 'Pembahasan tentang Syarat Wajib Shalat'),
(2, 'Rukun Shalat', 'Pembahasan tentang Rukun Shalat'),
(2, 'Sunnah Shalat', 'Pembahasan tentang Sunnah Shalat'),
(2, 'Shalat Wajib', 'Pembahasan tentang Shalat Wajib'),
(2, 'Shalat Sunnah Rawatib', 'Pembahasan tentang Shalat Sunnah Rawatib'),
(2, 'Shalat Jumat', 'Pembahasan tentang Shalat Jumat'),
(2, 'Shalat Jama’ dan Qashar', 'Pembahasan tentang Shalat Jama’ dan Qashar'),
(2, 'Shalat dalam Perjalanan', 'Pembahasan tentang Shalat dalam Perjalanan'),
(2, 'Tertib Shalat', 'Pembahasan tentang Tertib Shalat'),
(2, 'Hal yang Membatalkan Shalat', 'Pembahasan tentang Hal yang Membatalkan Shalat'),
(3, 'Definisi Puasa', 'Pembahasan tentang Definisi Puasa'),
(3, 'Syarat Sah Puasa', 'Pembahasan tentang Syarat Sah Puasa'),
(3, 'Rukun Puasa', 'Pembahasan tentang Rukun Puasa'),
(3, 'Niat dan Waktu Puasa', 'Pembahasan tentang Niat dan Waktu Puasa'),
(3, 'Puasa Wajib dan Sunnah', 'Pembahasan tentang Puasa Wajib dan Sunnah'),
(3, 'Hal yang Membatalkan Puasa', 'Pembahasan tentang Hal yang Membatalkan Puasa'),
(3, 'Kafarat dan Qadha', 'Pembahasan tentang Kafarat dan Qadha'),
(3, 'Puasa Ramadhan', 'Pembahasan tentang Puasa Ramadhan'),
(3, 'Puasa Syawal', 'Pembahasan tentang Puasa Syawal'),
(3, 'Puasa Arafah', 'Pembahasan tentang Puasa Arafah'),
(4, 'Pengertian Zakat', 'Pembahasan tentang Pengertian Zakat'),
(4, 'Syarat Wajib Zakat', 'Pembahasan tentang Syarat Wajib Zakat'),
(4, 'Jenis-jenis Zakat', 'Pembahasan tentang Jenis-jenis Zakat'),
(4, 'Zakat Fitrah', 'Pembahasan tentang Zakat Fitrah'),
(4, 'Zakat Maal', 'Pembahasan tentang Zakat Maal'),
(4, 'Nisab Zakat', 'Pembahasan tentang Nisab Zakat'),
(4, 'Zakat Profesi', 'Pembahasan tentang Zakat Profesi'),
(4, 'Mustahik Zakat', 'Pembahasan tentang Mustahik Zakat'),
(4, 'Waktu Pengeluaran', 'Pembahasan tentang Waktu Pengeluaran'),
(4, 'Distribusi Zakat', 'Pembahasan tentang Distribusi Zakat'),
(5, 'Pengertian Haji', 'Pembahasan tentang Pengertian Haji'),
(5, 'Syarat Haji', 'Pembahasan tentang Syarat Haji'),
(5, 'Rukun Haji', 'Pembahasan tentang Rukun Haji'),
(5, 'Wajib Haji', 'Pembahasan tentang Wajib Haji'),
(5, 'Tawaf', 'Pembahasan tentang Tawaf'),
(5, 'Sa’i', 'Pembahasan tentang Sa’i'),
(5, 'Wukuf di Arafah', 'Pembahasan tentang Wukuf di Arafah'),
(5, 'Larangan Saat Haji', 'Pembahasan tentang Larangan Saat Haji'),
(5, 'Dam Haji', 'Pembahasan tentang Dam Haji'),
(5, 'Umrah', 'Pembahasan tentang Umrah');

-- BAB 1: THAHARAH (100 soal)
-- Subbab 1: Pengertian Thaharah (10 soal)
INSERT INTO soal_kuis (id_subbab, soal, tipe_jawaban, pilihan_a, pilihan_b, pilihan_c, pilihan_d, jawaban_benar, poin) VALUES 
(1, 'Apa yang dimaksud dengan thaharah menurut bahasa?', 'radio', 'Kebersihan dan kesucian', 'Bersuci dengan air', 'Menghilangkan najis', 'Ritual keagamaan', 'Kebersihan dan kesucian', 10),
(1, 'Thaharah secara istilah syara adalah...', 'radio', 'Membersihkan badan dari kotoran', 'Menghilangkan hadats dan najis', 'Mandi dengan air suci', 'Berwudhu sebelum shalat', 'Menghilangkan hadats dan najis', 10),
(1, 'Berapa macam thaharah menurut hukum Islam?', 'radio', 'Satu macam', 'Dua macam', 'Tiga macam', 'Empat macam', 'Dua macam', 10),
(1, 'Thaharah dibagi menjadi dua, yaitu...', 'radio', 'Thaharah wajib dan sunnah', 'Thaharah hadats dan najis', 'Thaharah kecil dan besar', 'Thaharah air dan debu', 'Thaharah hadats dan najis', 10),
(1, 'Apa yang dimaksud dengan hadats?', 'radio', 'Kotoran yang terlihat', 'Sesuatu yang membatalkan wudhu', 'Najis yang menempel di badan', 'Air yang tidak suci', 'Sesuatu yang membatalkan wudhu', 10),
(1, 'Hadats dibagi menjadi berapa macam?', 'radio', 'Satu macam', 'Dua macam', 'Tiga macam', 'Empat macam', 'Dua macam', 10),
(1, 'Contoh hadats kecil adalah...', 'radio', 'Junub', 'Haid', 'Buang air kecil', 'Nifas', 'Buang air kecil', 10),
(1, 'Contoh hadats besar adalah...', 'radio', 'Kentut', 'Tidur', 'Junub', 'Menyentuh kemaluan', 'Junub', 10),
(1, 'Hikmah dari thaharah adalah...', 'radio', 'Mendapat pahala', 'Kebersihan dan kesehatan', 'Menjalankan perintah Allah', 'Semua jawaban benar', 'Semua jawaban benar', 10),
(1, 'Thaharah merupakan syarat sah untuk...', 'radio', 'Makan dan minum', 'Shalat dan thawaf', 'Tidur dan istirahat', 'Bekerja dan belajar', 'Shalat dan thawaf', 10),

-- Subbab 2: Macam-macam Air (10 soal)
(2, 'Berdasarkan hukum penggunaannya, air dibagi menjadi berapa macam?', 'radio', 'Dua macam', 'Tiga macam', 'Empat macam', 'Lima macam', 'Tiga macam', 10),
(2, 'Air yang suci dan mensucikan disebut...', 'radio', 'Air mutlak', 'Air mustamal', 'Air najis', 'Air muqayyad', 'Air mutlak', 10),
(2, 'Contoh air mutlak adalah...', 'radio', 'Air teh', 'Air hujan', 'Air kopi', 'Air sirup', 'Air hujan', 10),
(2, 'Air yang suci tapi tidak mensucikan disebut...', 'radio', 'Air mutlak', 'Air mustamal', 'Air muqayyad', 'Air najis', 'Air muqayyad', 10),
(2, 'Air laut termasuk jenis air...', 'radio', 'Air muqayyad', 'Air mustamal', 'Air mutlak', 'Air najis', 'Air mutlak', 10),
(2, 'Air yang tidak suci dan tidak mensucikan adalah...', 'radio', 'Air mutlak', 'Air mustamal', 'Air najis', 'Air muqayyad', 'Air najis', 10),
(2, 'Air sumur termasuk jenis...', 'radio', 'Air muqayyad', 'Air mutlak', 'Air najis', 'Air mustamal', 'Air mutlak', 10),
(2, 'Air yang tercampur dengan najis disebut...', 'radio', 'Air mutlak', 'Air najis', 'Air muqayyad', 'Air mustamal', 'Air najis', 10),
(2, 'Air es yang mencair termasuk...', 'radio', 'Air muqayyad', 'Air mutlak', 'Air najis', 'Air mustamal', 'Air mutlak', 10),
(2, 'Air yang boleh digunakan untuk berwudhu adalah...', 'radio', 'Air najis', 'Air muqayyad', 'Air mutlak', 'Air mustamal', 'Air mutlak', 10),

-- Subbab 3: Air yang Mensucikan (10 soal)
(3, 'Air yang dapat digunakan untuk bersuci adalah...', 'radio', 'Air mutlak saja', 'Air muqayyad saja', 'Air mutlak dan muqayyad', 'Semua jenis air', 'Air mutlak saja', 10),
(3, 'Syarat air yang mensucikan adalah...', 'radio', 'Suci dan tidak berubah', 'Banyak dan jernih', 'Dingin dan segar', 'Mengalir dan deras', 'Suci dan tidak berubah', 10),
(3, 'Air hujan dapat digunakan untuk...', 'radio', 'Minum saja', 'Mandi saja', 'Wudhu dan mandi', 'Mencuci pakaian saja', 'Wudhu dan mandi', 10),
(3, 'Air yang berubah karena tanah masih...', 'radio', 'Najis', 'Tidak boleh dipakai', 'Boleh dipakai untuk bersuci', 'Menjadi muqayyad', 'Boleh dipakai untuk bersuci', 10),
(3, 'Air zamzam termasuk air...', 'radio', 'Muqayyad', 'Najis', 'Mutlak', 'Mustamal', 'Mutlak', 10),
(3, 'Air yang tercampur dengan minyak...', 'radio', 'Tetap suci mensucikan', 'Menjadi najis', 'Menjadi muqayyad', 'Tidak boleh dipakai', 'Menjadi muqayyad', 10),
(3, 'Minimal air yang dapat digunakan untuk wudhu adalah...', 'radio', 'Satu liter', 'Satu mud', 'Dua qullah', 'Tidak ada batas minimal', 'Satu mud', 10),
(3, 'Air yang berubah warna karena najis...', 'radio', 'Tetap suci', 'Menjadi najis', 'Menjadi muqayyad', 'Masih boleh dipakai', 'Menjadi najis', 10),
(3, 'Air sungai yang jernih termasuk...', 'radio', 'Air muqayyad', 'Air najis', 'Air mutlak', 'Air mustamal', 'Air mutlak', 10),
(3, 'Air yang dipakai untuk mencuci najis...', 'radio', 'Tetap suci', 'Menjadi najis', 'Menjadi muqayyad', 'Menjadi mustamal', 'Menjadi najis', 10),

-- Subbab 4: Air mustamal (10 soal)
(4, 'Air mustamal adalah air yang...', 'radio', 'Sudah dipakai untuk bersuci', 'Tercampur dengan najis', 'Berubah warna dan rasa', 'Terlalu sedikit', 'Sudah dipakai untuk bersuci', 10),
(4, 'Hukum air mustamal menurut madzhab Syafii adalah...', 'radio', 'Suci dan mensucikan', 'Suci tapi tidak mensucikan', 'Najis', 'Makruh digunakan', 'Suci tapi tidak mensucikan', 10),
(4, 'Air bekas wudhu termasuk...', 'radio', 'Air mutlak', 'Air mustamal', 'Air najis', 'Air muqayyad', 'Air mustamal', 10),
(4, 'Air mustamal boleh digunakan untuk...', 'radio', 'Wudhu lagi', 'Minum', 'Mencuci pakaian', 'Semua jawaban benar', 'Mencuci pakaian', 10),
(4, 'Air yang menetes dari anggota wudhu...', 'radio', 'Tetap suci mensucikan', 'Menjadi mustamal', 'Menjadi najis', 'Menjadi muqayyad', 'Menjadi mustamal', 10),
(4, 'Air bekas mandi junub termasuk...', 'radio', 'Air mutlak', 'Air mustamal', 'Air najis', 'Air muqayyad', 'Air mustamal', 10),
(4, 'Perbedaan air mustamal dengan air najis adalah...', 'radio', 'Tidak ada perbedaan', 'Air mustamal masih suci', 'Air najis lebih kotor', 'Air mustamal lebih bersih', 'Air mustamal masih suci', 10),
(4, 'Air yang tersisa setelah wudhu dalam wadah...', 'radio', 'Menjadi najis', 'Tetap mutlak', 'Menjadi mustamal', 'Menjadi muqayyad', 'Tetap mutlak', 10),
(4, 'Hikmah larangan menggunakan air mustamal adalah...', 'radio', 'Menjaga kebersihan', 'Menghormati air', 'Kehati-hatian dalam bersuci', 'Semua jawaban benar', 'Semua jawaban benar', 10),
(4, 'Air mustamal yang bercampur dengan air mutlak...', 'radio', 'Tetap mustamal', 'Menjadi mutlak', 'Menjadi najis', 'Tergantung jumlahnya', 'Tergantung jumlahnya', 10),

-- Subbab 5: Najis dan Cara Mensucikan (10 soal)
(5, 'Najis menurut istilah syara adalah...', 'radio', 'Kotoran yang terlihat', 'Sesuatu yang kotor secara zahir', 'Sesuatu yang dianggap kotor oleh syara', 'Benda yang berbau busuk', 'Sesuatu yang dianggap kotor oleh syara', 10),
(5, 'Najis dibagi menjadi berapa macam berdasarkan tingkat kekotorannya?', 'radio', 'Dua macam', 'Tiga macam', 'Empat macam', 'Lima macam', 'Tiga macam', 10),
(5, 'Najis mukhoffafah adalah najis...', 'radio', 'Berat', 'Ringan', 'Sedang', 'Sangat berat', 'Ringan', 10),
(5, 'Contoh najis mukhoffafah adalah...', 'radio', 'Kotoran manusia', 'Kencing bayi laki-laki', 'Darah haid', 'Bangkai anjing', 'Kencing bayi laki-laki', 10),
(5, 'Najis mutawassithah adalah najis...', 'radio', 'Ringan', 'Sedang', 'Berat', 'Sangat ringan', 'Sedang', 10),
(5, 'Cara mensucikan najis mutawassithah adalah...', 'radio', 'Dipercik air', 'Dibasuh dengan air', 'Dihilangkan zatnya', 'Dijemur di matahari', 'Dibasuh dengan air', 10),
(5, 'Najis mugholladzah adalah najis...', 'radio', 'Ringan', 'Sedang', 'Berat', 'Sangat ringan', 'Berat', 10),
(5, 'Contoh najis mugholladzah adalah...', 'radio', 'Kencing kucing', 'Liur anjing', 'Kotoran ayam', 'Kencing sapi', 'Liur anjing', 10),
(5, 'Cara mensucikan najis mugholladzah adalah...', 'radio', 'Dibasuh sekali', 'Dibasuh 7 kali, salah satunya dengan tanah', 'Dipercik air', 'Dihilangkan zatnya', 'Dibasuh 7 kali, salah satunya dengan tanah', 10),
(5, 'Najis yang dimaafkan adalah...', 'radio', 'Najis mugholladzah', 'Najis dalam jumlah sedikit', 'Najis yang tidak terlihat', 'Najis yang sulit dihindari', 'Najis yang sulit dihindari', 10),

-- Subbab 6: Tayamum (10 soal)
(6, 'Tayamum secara bahasa berarti...', 'radio', 'Bersuci dengan air', 'Menuju atau menyengaja', 'Membersihkan diri', 'Menghilangkan najis', 'Menuju atau menyengaja', 10),
(6, 'Tayamum secara istilah adalah...', 'radio', 'Bersuci dengan air', 'Bersuci dengan debu suci', 'Bersuci dengan tanah', 'Bersuci tanpa air', 'Bersuci dengan debu suci', 10),
(6, 'Kapan tayamum diperbolehkan?', 'radio', 'Setiap saat', 'Ketika tidak ada air', 'Ketika malas wudhu', 'Ketika terburu-buru', 'Ketika tidak ada air', 10),
(6, 'Media yang boleh digunakan untuk tayamum adalah...', 'radio', 'Air dan tanah', 'Tanah dan debu suci', 'Pasir dan batu', 'Semua jawaban benar', 'Tanah dan debu suci', 10),
(6, 'Rukun tayamum ada berapa?', 'radio', 'Tiga', 'Empat', 'Lima', 'Enam', 'Empat', 10),
(6, 'Urutan rukun tayamum yang benar adalah...', 'radio', 'Niat, mengusap wajah, mengusap tangan', 'Niat, menepuk tanah, mengusap wajah, mengusap tangan', 'Menepuk tanah, niat, mengusap wajah, mengusap tangan', 'Mengusap wajah, mengusap tangan, niat', 'Niat, menepuk tanah, mengusap wajah, mengusap tangan', 10),
(7, 'Tayamum menggantikan...', 'radio', 'Wudhu saja', 'Mandi saja', 'Wudhu dan mandi', 'Shalat', 'Wudhu dan mandi', 10),
(6, 'Hal yang membatalkan tayamum adalah...', 'radio', 'Sama dengan yang membatalkan wudhu', 'Menemukan air', 'Hilangnya uzur', 'Semua jawaban benar', 'Semua jawaban benar', 10),
(6, 'Berapa kali menepuk tanah dalam tayamum?', 'radio', 'Sekali', 'Dua kali', 'Tiga kali', 'Tidak ada aturan', 'Dua kali', 10),
(6, 'Sunnah tayamum adalah...', 'radio', 'Membaca basmalah', 'Tertib dalam mengusap', 'Mendahulukan kanan', 'Semua jawaban benar', 'Semua jawaban benar', 10),

-- Subbab 7: Wudhu dan Rukunnya (10 soal)
(7, 'Wudhu secara bahasa berarti...', 'radio', 'Bersih dan indah', 'Suci dan jernih', 'Berkilau dan bersinar', 'Semua jawaban benar', 'Bersih dan indah', 10),
(7, 'Wudhu secara istilah adalah...', 'radio', 'Bersuci dengan air', 'Membersihkan anggota tertentu dengan air', 'Menghilangkan hadats kecil', 'Semua jawaban benar', 'Semua jawaban benar', 10),
(7, 'Rukun wudhu ada berapa?', 'radio', 'Empat', 'Lima', 'Enam', 'Tujuh', 'Enam', 10),
(7, 'Rukun wudhu yang pertama adalah...', 'radio', 'Membasuh wajah', 'Niat', 'Membasuh tangan', 'Berkumur', 'Niat', 10),
(7, 'Batas membasuh wajah dalam wudhu adalah...', 'radio', 'Dari dahi sampai dagu', 'Dari telinga ke telinga', 'Dari batas rambut sampai dagu, dari telinga ke telinga', 'Seluruh kepala', 'Dari batas rambut sampai dagu, dari telinga ke telinga', 10),
(7, 'Membasuh tangan dalam wudhu sampai...', 'radio', 'Pergelangan tangan', 'Siku', 'Ketiak', 'Bahu', 'Siku', 10),
(7, 'Mengusap sebagian kepala hukumnya...', 'radio', 'Sunnah', 'Wajib', 'Mustahab', 'Mubah', 'Wajib', 10),
(7, 'Membasuh kaki dalam wudhu sampai...', 'radio', 'Jari kaki', 'Mata kaki', 'Pergelangan kaki', 'Betis', 'Mata kaki', 10),
(7, 'Tertib dalam wudhu hukumnya...', 'radio', 'Sunnah', 'Wajib', 'Mustahab', 'Mubah', 'Wajib', 10),
(7, 'Doa setelah wudhu dimulai dengan...', 'radio', 'Asyhadu an la ilaha illallah', 'Allahumma ajalni minat tawwabin', 'Bismillahirrahmanirrahim', 'Subhanallahi wa bihamdihi', 'Asyhadu an la ilaha illallah', 10),

-- Subbab 8: Sunnah Wudhu (10 soal)
(8, 'Membaca basmalah sebelum wudhu hukumnya...', 'radio', 'Wajib', 'Sunnah', 'Mubah', 'Mustahab', 'Sunnah', 10),
(8, 'Mencuci telapak tangan sebelum wudhu termasuk...', 'radio', 'Rukun', 'Syarat', 'Sunnah', 'Wajib', 'Sunnah', 10),
(8, 'Berkumur dalam wudhu hukumnya...', 'radio', 'Wajib', 'Sunnah', 'Rukun', 'Syarat', 'Sunnah', 10),
(8, 'Menghirup air ke hidung (istinsyaq) termasuk...', 'radio', 'Rukun wudhu', 'Sunnah wudhu', 'Syarat wudhu', 'Wajib wudhu', 'Sunnah wudhu', 10),
(8, 'Mengusap telinga dalam wudhu hukumnya...', 'radio', 'Wajib', 'Sunnah', 'Rukun', 'Syarat', 'Sunnah', 10),
(8, 'Menyela-nyela jari kaki termasuk...', 'radio', 'Rukun wudhu', 'Sunnah wudhu', 'Syarat wudhu', 'Wajib wudhu', 'Sunnah wudhu', 10),
(8, 'Mendahulukan anggota kanan dalam wudhu adalah...', 'radio', 'Wajib', 'Sunnah', 'Rukun', 'Syarat', 'Sunnah', 10),
(8, 'Membasuh anggota wudhu tiga kali adalah...', 'radio', 'Wajib', 'Sunnah', 'Rukun', 'Syarat', 'Sunnah', 10),
(8, 'Berdoa setelah wudhu hukumnya...', 'radio', 'Wajib', 'Sunnah', 'Rukun', 'Syarat', 'Sunnah', 10),
(8, 'Tidak berbicara saat wudhu termasuk...', 'radio', 'Wajib', 'Sunnah', 'Rukun', 'Haram', 'Sunnah', 10),

-- Subbab 9: Hal yang Membatalkan Wudhu (10 soal)
(9, 'Keluar sesuatu dari qubul atau dubur membatalkan wudhu karena...', 'radio', 'Najis', 'Hadats', 'Kotor', 'Bau', 'Hadats', 10),
(9, 'Tidur yang membatalkan wudhu adalah...', 'radio', 'Tidur sebentar', 'Tidur dalam keadaan duduk', 'Tidur tidak dalam keadaan duduk', 'Semua tidur', 'Tidur tidak dalam keadaan duduk', 10),
(9, 'Hilang akal karena gila atau pingsan...', 'radio', 'Tidak membatalkan wudhu', 'Membatalkan wudhu', 'Makruh', 'Diragukan', 'Membatalkan wudhu', 10),
(9, 'Menyentuh kemaluan dengan telapak tangan...', 'radio', 'Tidak membatalkan wudhu', 'Membatalkan wudhu', 'Sunnah berwudhu', 'Makruh', 'Membatalkan wudhu', 10),
(9, 'Bersentuhan kulit antara laki-laki dan perempuan yang bukan mahram...', 'radio', 'Selalu membatalkan wudhu', 'Tidak membatalkan wudhu', 'Membatalkan jika dengan syahwat', 'Makruh', 'Membatalkan jika dengan syahwat', 10),
(9, 'Keluar darah dari tubuh yang banyak...', 'radio', 'Tidak membatalkan wudhu', 'Membatalkan wudhu', 'Makruh', 'Sunnah berwudhu', 'Membatalkan wudhu', 10),
(9, 'Muntah yang membatalkan wudhu adalah...', 'radio', 'Muntah sedikit', 'Muntah banyak', 'Semua muntah', 'Tidak ada muntah yang membatalkan', 'Muntah banyak', 10),
(9, 'Makan daging unta...', 'radio', 'Tidak membatalkan wudhu', 'Membatalkan wudhu', 'Makruh', 'Sunnah berwudhu', 'Membatalkan wudhu', 10),
(9, 'Murtad (keluar dari Islam)...', 'radio', 'Tidak membatalkan wudhu', 'Membatalkan wudhu', 'Makruh', 'Diragukan', 'Membatalkan wudhu', 10),
(9, 'Bersuara keras saat wudhu...', 'radio', 'Membatalkan wudhu', 'Tidak membatalkan wudhu', 'Makruh', 'Haram', 'Tidak membatalkan wudhu', 10),

-- Subbab 10: Mandi Wajib (10 soal)
(10, 'Mandi wajib disebut juga...', 'radio', 'Mandi sunnah', 'Mandi janabah', 'Mandi istinja', 'Mandi biasa', 'Mandi janabah', 10),
(10, 'Sebab-sebab mandi wajib ada...', 'radio', 'Tiga', 'Empat', 'Lima', 'Enam', 'Lima', 10),
(10, 'Keluar mani karena syahwat mewajibkan...', 'radio', 'Wudhu', 'Mandi', 'Tayamum', 'Tidak ada yang wajib', 'Mandi', 10),
(10, 'Haid dan nifas mewajibkan...', 'radio', 'Wudhu', 'Mandi setelah suci', 'Tayamum', 'Tidak ada yang wajib', 'Mandi setelah suci', 10),
(10, 'Masuk Islam bagi orang kafir mewajibkan...', 'radio', 'Wudhu', 'Mandi', 'Tayamum', 'Tidak ada yang wajib', 'Mandi', 10),
(10, 'Rukun mandi wajib ada...', 'radio', 'Dua', 'Tiga', 'Empat', 'Lima', 'Dua', 10),
(10, 'Rukun mandi wajib adalah...', 'radio', 'Niat dan membasuh seluruh badan', 'Niat dan berkumur', 'Membasuh kepala dan badan', 'Niat dan berdoa', 'Niat dan membasuh seluruh badan', 10),
(10, 'Sunnah mandi wajib adalah...', 'radio', 'Berkumur dan istinsyaq', 'Membasuh kemaluan', 'Wudhu terlebih dahulu', 'Semua jawaban benar', 'Semua jawaban benar', 10),
(10, 'Orang yang junub dilarang...', 'radio', 'Makan dan minum', 'Shalat dan thawaf', 'Tidur dan istirahat', 'Berbicara', 'Shalat dan thawaf', 10),
(10, 'Mandi wajib menggantikan...', 'radio', 'Wudhu', 'Tayamum', 'Wudhu dan tayamum', 'Tidak menggantikan apa-apa', 'Wudhu dan tayamum', 10);
